### ISSUE TITLE
Failed to get handle for right Joy-Con or Pro Controller, exiting

### ISSUE THREAD

**Issue by yaomtc** [shinyquagsire23/HID-Joy-Con-Whispering#16]
I've compiled it successfully but when I plug in the Pro Controller via USB and run uinputdriver, I get:

> Failed to get handle for right Joy-Con or Pro Controller, exiting...

I'm on Ubuntu 18.04.1.

**Comment by Diatomo** [comment]
Hey I'm on Ubuntu 16.04. I fixed this by running uinputdriver with 'sudo'

**Comment by yaomtc** [comment]
I don't have Ubuntu installed anymore but that was probably my issue, closing
